"use client";

import { Box, Flex, Spinner, Text } from "@chakra-ui/react"; // Added Spinner, Text
import { ReactNode, useEffect } from "react";
import { useRouter } from "next/navigation"; // Use next/navigation
import { GameHeader } from "@/components/layout/GameHeader";
import { GameFooter } from "@/components/layout/GameFooter";
import { SettingsModal } from "@/components/layout/SettingsModal";
import { InventoryModal } from "@/components/game/InventoryModal";
import { useSoundManager } from "@/hooks/useSoundManager";
import { useGameStore } from "@/store/gameStore";

interface GameLayoutProps {
  children: ReactNode;
}

export default function GameLayout({ children }: GameLayoutProps) {
  const router = useRouter();
  const {
    gameId, // Get gameId
    playerStats,
    inventory,
    isProcessingCommand,
    isStartingGame, // Get the start game loading state
    isInventoryOpen,
    isSettingsOpen,
    animationSpeed,
    masterVolume,
    effectsVolume,
    // Actions
    sendCommand,
    useItem,
    equipItem,
    dropItem,
    toggleInventory,
    toggleSettings,
    setAnimationSpeed,
    setMasterVolume,
    setEffectsVolume,
    // No need for loadInitialData here anymore, startGame handles it
  } = useGameStore();

  const soundManager = useSoundManager();

  // --- Redirect Logic ---
  useEffect(() => {
    // Check gameId AND playerStats presence after initial loading phase
    // This makes the check less sensitive to the exact moment gameId updates
    if (!isStartingGame && (!gameId || !playerStats)) {
      console.log(
        "GameLayout: Missing gameId or playerStats, redirecting to home. gameId:",
        gameId,
        "isStartingGame:",
        isStartingGame
      );
      router.replace("/"); // Use replace to avoid adding to history stack
    } else {
      console.log(
        "GameLayout: Guard passed. gameId:",
        gameId,
        "isStartingGame:",
        isStartingGame
      );
    }
    // Add playerStats to dependency array
  }, [gameId, playerStats, isStartingGame, router]);

  // --- Volume Sync Effects ---
  useEffect(() => {
    soundManager.setMasterVolume(masterVolume);
  }, [masterVolume, soundManager]);

  useEffect(() => {
    soundManager.setEffectsVolume(effectsVolume);
  }, [effectsVolume, soundManager]);

  // --- Render Logic ---

  // Show loading state specifically while the game is being generated by the backend
  if (isStartingGame) {
    return (
      <Flex
        justify="center"
        align="center"
        minH="100vh"
        bg="brand.bgDark"
        direction="column"
        gap={4}
      >
        <Spinner size="xl" color="brand.accent" thickness="4px" />
        <Text color="brand.textLight" fontSize="lg">
          Generating your adventure...
        </Text>
      </Flex>
    );
  }

  // Show loading or null state if gameId is missing but somehow passed the redirect
  // (or if playerStats are not yet available right after start)
  if (!gameId || !playerStats) {
    // This state might be brief or indicate an error after starting
    // The redirect should handle the main case of accessing /game directly
    return (
      <Flex
        justify="center"
        align="center"
        minH="100vh"
        bg="brand.bgDark"
        direction="column"
        gap={4}
      >
        {/* Can show a different loading/error or just the spinner */}
        <Spinner size="xl" color="brand.accent" thickness="4px" />
        <Text color="brand.textLight">Loading game data...</Text>
      </Flex>
    );
  }

  // --- Render Full Game UI ---
  return (
    <Flex direction="column" minH="100vh" bg="brand.bgDark" color="brand.text">
      <GameHeader
        playerStats={playerStats}
        onOpenSettings={() => toggleSettings(true)}
        onOpenInventory={() => toggleInventory(true)}
      />

      <Box
        as="main"
        flex="1"
        p={4}
        display="flex"
        flexDirection="column"
        overflow="hidden"
      >
        {children}
      </Box>

      <GameFooter
        onCommandSubmit={sendCommand}
        isProcessingCommand={isProcessingCommand}
      />

      <SettingsModal
        isOpen={isSettingsOpen}
        onClose={() => toggleSettings(false)}
        masterVolume={masterVolume}
        effectsVolume={effectsVolume}
        animationSpeed={animationSpeed}
        onMasterVolumeChange={setMasterVolume}
        onEffectsVolumeChange={setEffectsVolume}
        onAnimationSpeedChange={setAnimationSpeed}
      />

      <InventoryModal
        isOpen={isInventoryOpen}
        onClose={() => toggleInventory(false)}
        items={inventory}
        onUseItem={useItem}
        onEquipItem={equipItem}
        onDropItem={dropItem}
      />
    </Flex>
  );
}
